### ISSUE TITLE
Authentication plugin 'caching_sha2_password' is not supported

### ISSUE THREAD

**Issue by nSedrickm** [sherlockwisdom/Afkanerd-Deku-Python-Port#6]
**Command(s) run**
```bash
python daemon.py

python daemon_received.py 
```

**Resulting Error message**
Authentication plugin 'caching_sha2_password' is not supported

**Comment by sherlockwisdom** [comment]
What python version are you using? 
If python3 isn't your default then run them with python3 daemon.py and python3 daemon_received.py
